apiVersion: v1
kind: Pod
metadata:
  name: logstash-monasca
  labels:
    k8s-app: logstash-monasca
spec:
  containers:
  - name: logstash-monasca
    image: taimir93/logstash-monasca:0.17
    command:
      - /run.sh
      - http://10.140.18.77:8070
      - http://10.140.18.87:5000
      - csi
      - csi-operator
      - password
      - default
    resources:
      limits:
        memory: 500Mi
        cpu: 1000m
      requests:
        cpu: 200m
        memory: 300Mi
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
    # because of logstash
    tty: true
    # for debugging
    stdin: true
  terminationGracePeriodSeconds: 30
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
